FROM debian:latest

# Instala dependencias previas y añade el repositorio Sury
RUN apt-get update && apt-get install -y \
    lsb-release \
    apt-transport-https \
    ca-certificates \
    gnupg \
    wget mariadb-client

# Añade la clave GPG del repositorio Sury y lo añade a la lista de fuentes
RUN wget -qO - https://packages.sury.org/php/apt.gpg | apt-key add - && \
    echo "deb https://packages.sury.org/php/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/sury-php.list

# Instala Nginx, PHP 7.4 y dependencias
RUN apt-get update && apt-get install -y \
    nginx \
    php7.4 \
    php7.4-fpm \
    php7.4-mysql \
    php7.4-zip \
    php7.4-curl \
    php7.4-xml \
    php7.4-intl \
    php7.4-mbstring \
    php7.4-gd \
    wget unzip && \
    rm -rf /var/lib/apt/lists/*

# Descarga OwnCloud
RUN wget https://download.owncloud.com/server/stable/owncloud-complete-latest.zip -O /owncloud.zip && \
    unzip /owncloud.zip -d /var/www/html/ && \
    chown -R www-data:www-data /var/www/html/owncloud && \
    chmod -R 755 /var/www/html/owncloud

# Copia la configuración de Nginx y el script de instalación
COPY default /etc/nginx/sites-available/default
COPY setup-owncloud.sh /setup-owncloud.sh
RUN chmod +x /setup-owncloud.sh

# Iniciar servicios y ejecutar el script de OwnCloud
CMD ["/bin/bash", "-c", "php-fpm7.4 -D && nginx && tail -f /dev/null"]
#CMD ["/bin/bash", "-c", "php-fpm7.4 -D && nginx && /setup-owncloud.sh && tail -f /dev/null"]
