# Utiliza la imagen base de Ubuntu 20.04
FROM ubuntu:20.04

# Actualiza los paquetes e instala OpenSSL y Nginx
RUN apt-get update && apt-get install -y openssl && apt-get install -y nginx-full && rm -rf /etc/nginx/nginx.conf

# Copia la configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Crea el directorio de certificados y los archivos
RUN mkdir -p /etc/nginx/certs
RUN sh -c "openssl req -x509 -nodes -days 365 \
-subj '/C=US/ST=State/L=City/O=Organization/CN=jorgelpz.com' \
-newkey rsa:2048 -keyout '/etc/ssl/certs/jorgelpz.key' -out '/etc/ssl/certs/jorgelpz.crt'"

# Exponer los puertos HTTP y HTTPS
EXPOSE 80 443

# Inicia Nginx en primer plano
CMD ["nginx", "-g", "daemon off;"]
